In [125]:
%matplotlib notebook
from scipy.io import loadmat
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import metrics
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import (NeighborhoodComponentsAnalysis,KNeighborsClassifier)
import numpy as np

mat_contents = loadmat("dataset/thyroidTrain.mat")
testInputs = mat_contents['testThyroidInput']
trainInputs = mat_contents['trainThyroidInput']
trainOutputs = mat_contents['trainThyroidOutput']

print("TestInputs shape",testInputs.shape)
print("TrainInputs shape",trainInputs.shape)
print("TrainOutputs",trainOutputs.shape)
#ont hot vector to integer mapping 0-> normal , 1->hypothyroid , 2->hyperthyroid
trainOutputSingleVal = [np.where(r==1)[0][0] for r in trainOutputs]

print("sample train input\n",trainInputs[:3])
print("sample train output\n",trainOutputs[:3])
print("trainOutputSingleVal",trainOutputSingleVal[5:8])


print("SVM training and spliting..........")

X_train, X_test, y_train, y_test = train_test_split(trainInputs, trainOutputSingleVal, test_size=0.3)

# Linear Kernel
clfSVM = svm.SVC(kernel='linear') 

#Train the model using the training sets
clfSVM.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clfSVM.predict(X_test)

print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
y_SVM_pred = clfSVM.predict(testInputs)
print("Predicte output for test Input using liner SVM",y_SVM_pred[:10])
print("thyroid counts :\n")
unique, counts = np.unique(y_SVM_pred, return_counts=True)
print( np.asarray((unique, counts)).T)

clfMLP = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(8, 2))
clfMLP.fit(X_train, y_train)
y_MLPpred = clfMLP.predict(X_test)
print("MLP Accuracy:",metrics.accuracy_score(y_test, y_MLP_pred))
MLP_OP_pred = clfMLP.predict(testInputs)

print("Predicte output for test Input using MLP",MLP_OP_pred[:10])
print("thyroid counts :\n")
unique, counts = np.unique(MLP_OP_pred, return_counts=True)
print( np.asarray((unique, counts)).T)

print("KNN")

X_train_knn, X_test_knn, y_train_knn, y_test_knn = train_test_split(trainInputs, trainOutputSingleVal, test_size=0.3)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_knn, y_train_knn)
y_pred_knn = knn.predict(X_test_knn)
print("KNN Accuracy:",metrics.accuracy_score(y_test_knn, y_pred_knn))

KNN_OP_pred = knn.predict(testInputs)

print("Predicte output for test Input using MLP",KNN_OP_pred[:10])
print("thyroid counts :\n")
unique, counts = np.unique(KNN_OP_pred, return_counts=True)
print( np.asarray((unique, counts)).T)

TestInputs shape (2200, 21)
TrainInputs shape (5000, 21)
TrainOutputs (5000, 3)
sample train input
 [[2.8000e-01 0.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 2.5000e-03 2.6000e-02
  1.7900e-01 1.5500e-01 1.1500e-01]
 [4.5000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 2.0000e-05 1.4000e-02
  1.4400e-01 9.9000e-02 1.4516e-01]
 [7.7000e-01 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00 0.0000e+00 1.0000e+00 1.0000e+00 0.0000e+00
  0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 1.8900e-03 1.8000e-02
  1.1100e-01 9.6000e-02 1.1500e-01]]
sample train output
 [[0 0 1]
 [0 0 1]
 [0 0 1]]
trainOutputSingleVal [2, 1, 2]
SVM training and spliting..........
Accuracy: 0.9246666666666666
Predicte output for test Input usi